server:
  port: 8082
spring:
  application:
    name: auto-service
  doc:
    swagger-ui:
      path: /documentacion
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost